### ISSUE TITLE
TODO lists

### ISSUE THREAD

**Issue by zhmz90** [OpenGene/HTSLIB.jl#1]
- [x] bam_itr_next  bug
- [x] support not real path for the function open 
- [x] test
- [x] document
- [x] err signal handle
- [x] build shared library

**Comment by zhmz90** [comment]
There are a lot of work to do to implement `query` so that it is better to make a useable bam/sam read/write library first.

**Comment by zhmz90** [comment]
just finished HTSFile
